import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
const root=resolve(import.meta.dirname,"..");
const [builds,classes,guides,terms,seoPages,site]=await Promise.all(["builds","classes","guides","dictionary","seo-pages","site"].map(name=>readFile(resolve(root,`data/${name}.json`),"utf8").then(JSON.parse)));
const base=site.baseUrl;
const date=site.lastUpdated;
const indexableBuilds=builds.filter(x=>x.status==="verified");
const urls=[...new Set(["/","/builds/","/classes/","/gear-check/","/class-check/","/beginner-guide/","/guides/beginner-build/","/dictionary/","/tier-list/","/league-starter/","/poe2-1-0/","/about/","/editorial-policy/","/privacy/","/terms/",...classes.map(x=>`/classes/${x.slug}/`),...indexableBuilds.map(x=>`/builds/${x.classSlug}/${x.slug}/`),...guides.map(x=>`/guides/${x.slug}/`),...terms.map(x=>`/dictionary/${x.slug}/`),...seoPages.map(x=>x.path)])];
const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map((path,i)=>`  <url><loc>${base}${path}</loc><lastmod>${date}</lastmod><priority>${i===0?"1.0":path.startsWith("/builds/")||path.startsWith("/classes/")?"0.9":"0.7"}</priority></url>`).join("\n")}\n</urlset>\n`;
await writeFile(resolve(root,"sitemap.xml"),xml);
console.log(`Generated sitemap with ${urls.length} URLs.`);
